### PR TITLE
Add asum, empty to CorePrelude

### LINKED ISSUE #64: `asum` missing
I am debating on using `basic-prelude` or `base-prelude`.

The fact that `basic-prelude` doesn't expose `asum` from `Data.Foldable` is currently preventing me to consider `basic-prelude`.

Is there any reason why it is not included ? Would you consider including it ?

### PR DESCRIPTION
**Pull request by PierreR**
This is to fix #64. Let's me know if it is ok by you

### CODE REVIEW

**Comment by PierreR** [comment]
This is to fix #64. Let's me know if it is ok by you

**Comment by PierreR** [comment]
Maybe I should add `asum` only for now. Add the deprecation pragma as a second commit and wait for the complete deletion of `empty = mempty` to go ahead and add `empty` to CorePrelude ...

**Comment by PierreR** [comment]
I ended up doing what I suggested in my previous message ;-)

**Comment by DanBurton** [comment]
:+1:

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
