### PR TITLE
Remove read args, switch to safe-exceptions

### PR DESCRIPTION
**Pull request by snoyberg**
Pinging @gregwebs and @DanBurton for feedback. Greg: I think you weren't in favor of ReadArgs in the first place. For safe-exceptions, I think it's overall a better approach, and provides async safety.

### CODE REVIEW

**Comment by singpolyma** [comment]
Removing GHC 7.6 support I a pretty big deal. Will block be from using newer versions of this library on many of my environments.

**Comment by DanBurton** [comment]
I have no strong feelings about this.

How hard would it be to add GHC 7.6 support to safe-exceptions?

**Comment by snoyberg** [comment]
See https://travis-ci.org/fpco/safe-exceptions/jobs/158641197 for the build failure, it's due to the lack of the `SomeAsyncException` type before GHC 7.8. It's theoretically possible to work around that, but not trivially _or_ reliably.

I'm actually pretty shocked to hear that someone is stuck on GHC 7.6, what systems are still sticking with it?

**Comment by singpolyma** [comment]
Anything based on Ubuntu 14.04, which includes the most recent Trisquel release, among others.

**Comment by snoyberg** [comment]
There are at least three common ways of using a different GHC: Stack, PPAs,
and manual installation. I can't imagine this is the only library you'd be
stuck in an older version for with GHC 7.6

**Comment by snoyberg** [comment]
I've already dropped ReadArgs from master. And PR #81 simplify removes the exception handling functionality entirely, so closing this PR.

**Pull request closed without merging**
